# Generated by Django 4.1.7 on 2023-03-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
