# Generated by Django 4.1.7 on 2023-03-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
